/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation 

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').Sidebarsconfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
    'intro',
    'features',
    'modhighlights',
    'requirements',
    'minimumspecs',
    'setupinstructions',
    'controllerinstructions',
    'updating',
    'modquickreference',
    'frequentlyaskedquestions',
    'supportfeedback',
    'credits',
  ],
  gallerySidebar: [
    'userinterface',
    'mechanics',
    'characters',
    'creatures',
    'armor',
    'weapons',
    'mojavewasteland',
    'thestrip',  
    'capitalwasteland',
    'megaton',
    'drywells',
    'lakehavasu',
    'arroyocanyon',
    'deadmoney',
    'honesthearts',
    'lonesomeroad',
    'oldworldblues',
    'anchorage',
    'thepitt',
    'pointlookout',
    'mothershipzeta',
    'brokensteel',
    'casinointeriors',
    'houseinteriors',
    'industrialinteriors',
    'bunkerinteriors',
    'undergroundinteriors',
    'deadmoneyinteriors',
    'oldworldbluesinteriors',
    'anchorageinteriors',
    'thepittinteriors',
  ],
  resourcesSidebar: [
   'resourcesoverview',
   'importantlinks',
   'losslessscalingguide',
   'stars',
   'sweetloadorder',
   'sweetrecommendedmods',
   'troubleshooting',
  ],
  changelogSidebar: [
    'changelog1.3.1.1',
    'changelog1.3.1.0',
    'changelog1.3.0.2',
    'changelog1.3.0.1',
    'changelog1.3.0.0',
    'changelog1.2.1.0',
    'changelog1.2.0.4',
    'changelog1.2.0.3',
    'changelog1.2.0.2',
    'changelog1.2.0.1',
    'changelog1.2.0.0',
    'changelog1.1.1.0',
    'changelog1.1.0.1',
    'changelog1.1.0.0',
    'changelog1.0.0.0',
  ],
};

export default sidebars;
